# SPDX-FileCopyrightText: 2022 Björn Fiedler <fiedler@sra.uni-hannover.de>
# SPDX-FileCopyrightText: 2024 Andreas Kässens <kaessens@sra.uni-hannover.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM debian:bookworm-backports
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin

# graph tool is not installed to /usr/include
ENV CPATH=/usr/local/lib/python3.11/dist-packages/graph_tool/include

# go packages go here
ENV GOBIN=/usr/local/bin/

RUN apt update && apt-get install -qq\
	clang clang-14 clang-format-14 llvm-14-dev lld-14\
	python3 python3-pip tmux build-essential ninja-build git\
	binutils-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib\
	binutils-riscv64-unknown-elf gcc-riscv64-unknown-elf libstdc++-12-dev-riscv64-cross\
	bash-completion gdb-multiarch pkg-config z3 graphviz\
	libsparsehash-dev gperf cmake g++-multilib libboost-python-dev libboost-graph-dev\
	python3-matplotlib python3-pykwalify python3-pyelftools\
	npm device-tree-compiler autoconf file golang\
	stlink-tools qemu-system\
	cloc lsb-release libelf-dev binutils-dev\
	wget zsh -t bookworm-backports

# https://peps.python.org/pep-0668/
RUN	rm /usr/lib/python3.11/EXTERNALLY-MANAGED

# outdated versions in debian
RUN pip3 install versuchung cython meson pydot==4.0.1 pyserial intelhex

# compatibility with apt installed cython
RUN ln -s /usr/local/bin/cython /usr/bin/cython3

# gllvm must be installed via go package manager
RUN go install github.com/SRI-CSL/gllvm/cmd/...@master

# install graph-tool from upstream repo
# FIX: use trusted=yes to bypass the expired GPG key on the skewed.de repo
RUN echo "deb [trusted=yes] https://downloads.skewed.de/apt $(lsb_release -s -c) main" > \
    /etc/apt/sources.list.d/skewed.list \
    && apt-get update \
    && apt-get install -y python3-graph-tool

# install typst for rendering eval results
RUN wget https://github.com/typst/typst/releases/download/v0.14.2/typst-x86_64-unknown-linux-musl.tar.xz \
  && tar xvf typst-x86_64-unknown-linux-musl.tar.xz \
  && cp typst-x86_64-unknown-linux-musl/typst /usr/local/bin/typst

# pre-download parrot and configure (for artifact releases)
#RUN git clone --depth 1 https://github.com/luhsra/parrot --branch ecrts26 \
#	&& cd parrot \
#	&& meson setup build --native-file native-debian.ini -Denable_posix=true -Denable_arm=true -Dbuild_hypersse_xen=true
#
#LABEL description="PARROT analysis framework"