build:
  tags: ["sra.labor"]
  image: scm.sra.uni-hannover.de:5050/research/parrot
  interruptible: true
  only: [main, citest]
  script:
    - export GIT_CONFIG_GLOBAL=$PWD/ci_gitconfig
    - git config --global --add url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/".insteadOf "ssh://git@scm.sra.uni-hannover.de"
    - git config --global --add url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/".insteadOf "https://scm.sra.uni-hannover.de"
    - meson setup build --native-file native-debian.ini -Denable_posix=true -Denable_arm=true -Denable_riscv=true -Dbuild_posix_apps=true -Dbuild_zephyr_apps=true -Dbuild_hypersse_xen=true -Dbuild_generator_tests=true
    - cd build
    - meson compile |& tee build_all.log
    - meson test --suite posix --suite zephyr --suite hypersse_xen --suite autosar_generator |& tee test.log
  artifacts:
    when: always
    paths:
      - build/*.log
      - build/meson-logs/testlog.txt
