[constants]
arm_triple = 'arm-none-eabi'
arm64_triple = 'aarch64-none-elf'
riscv_triple = 'riscv64-elf'

[binaries]
cython = '/usr/bin/cython3'
llvm-config = '/usr/bin/llvm-config-14'

[properties]
arm_triple          = arm_triple
arm_include_path    = '/usr' / arm_triple / 'include'
arm_link_path       = '/usr' / arm_triple / 'lib'
arm_cxx_dir         = '/usr' / arm_triple / 'include/c++' / '@gcc_arm_version@'
arm_gcc_dir         = '/usr/lib/gcc' / arm_triple / '@gcc_arm_version@'

arm64_triple          = arm64_triple
arm64_include_path    = '/usr' / arm64_triple / 'include'
arm64_link_path       = '/usr' / arm64_triple / 'lib'
arm64_cxx_dir         = '/usr' / arm64_triple / 'include/c++' / '@gcc_arm64_version@'
arm64_gcc_dir         = '/usr/lib/gcc' / arm64_triple / '@gcc_arm64_version@'

#riscv_triple        = riscv64-linux-gnu
#riscv_include_path  = '/usr' / riscv_triple / 'include/c++' / '@gcc_riscv_version@'
#riscv_link_path     = '/usr' / riscv_triple / 'lib'
#riscv_cxx_dir       = '/usr' / riscv_triple / 'include/c++' / '@gcc_riscv_version@'
#riscv_gcc_dir       = '/usr/lib/gcc' / riscv_triple / '@gcc_riscv_version@'

riscv_triple        = riscv_triple
riscv_include_path  = '/usr' / riscv_triple / 'include'
riscv_link_path     = '/usr' / riscv_triple / 'lib'
riscv_cxx_dir       = '/usr' / riscv_triple / 'include/c++'
riscv_gcc_dir       = '/usr/lib/gcc' / riscv_triple / '@gcc_riscv_version@'